#!/bin/bash
set -e
set -o pipefail
clear
if [ "$(id -u)" != "1000" ]; then
	echo "Start script with root privlages"
	exit
fi
echo "Welcome to the setup"
echo "Have you already made a disk configuration y/n"
read dishch
if [ "$dishch" != "y" ] && [ "$diskch" != "n" ]; then
	while [ "$diskch" != "y" ] && [ "$diskch" != "n" ]; do
		echo "please give a acceptable answear"
		read diskch
	done
fi
if [ "$diskch" == "n" ]; then
	echo "Which of the following drives do you want to use"
	lsblk 
	echo "remember drive number of the partitions created so they can be mounted"
	read disk
	cgdisk /dev/$disk
fi
echo "which drive is the root drive"
read disk
mkfs.ext4 /dev/$disk
mount /dev/$disk /mnt
echo "which drive is the boot drive"
read bootdisk
mkfs.fat -F32 /dev/$bootdisk
mkdir /mnt/boot
mount /dev/$bootdisk /mnt/boot
echo "which drive is the swap drive (no input if you do not want swap)"
read disk
if [ "$disk" != "" ]; then
	mkswap /dev/$disk
	swapon /dev/$disk
fi
pacman -Sy pacman-contrib lspci
wait 5
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
echo "generating mirrorlist may take a while"
rankmirrors -n 6 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist
sed -i -e 's/#COLOR/COLOR/g' /etc/pacman.conf
sed -i -e 's/ParallelDownloads = 5/ParallelDownloads = 50/g' /etc/pacman.conf
echo "ILoveCandy" >> /etc/pacman.conf
pacstrap -K /mnt hyprlock hypridle ntfs-3g ufw os-prober base linux base-devel waybar hyprland git grub efibootmgr sddm wayland rofi kitty ttf-ubuntu-mono-nerd bash-completions code firefox pavucontrol thunar sof-firmware wpa_supplicant dhcpcd htop btop intel-ucode linux-firmware-mediatek linux-firmware-nvidia
arch-chroot /mnt
systemctl enable wpa_supplicant
systemctl enable dhcpcd
systemctl enable ufw
systemctl enable sddm
ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
echo 'LANG="sv_SE.UTF-8"' > /etc/locale.conf
sed -i -e 's/#sv_SE.UTF-8 UTF-8/sv_SE.UTF-8 UTF-8/g' locale.gen
locale-gen
clear
echo "Making user accounts please give name"
read name
useradd -m -g users -G wheel,storage,power -s /bin/bash $(name)
passwd $(name)
echo "Please enter root password"
passwd
clear
grub-install --efi-directory="$(bootdisk)" --target=x86_64-efi --bootloader-id=ARCH
sed -i -e 's/#GRUB_DISABLE_OS_PROBER=false/GRUB_DISABLE_OS_PROBER=false/g' /etc/default/grub
clear
echo "please enter windows main drive so that grub can auto add it"
lsblk
read disk
mount /dev/$(disk) /mnt
clear
grub-mkconfig -o /boot/grub/grub.cfg
clear
#git
su $(name)
cd main-rice
test -d ~/.config/ || mkdir ~/.config/
mkdir ~/.config/hypr
mkdir ~/.config/waybar
mkdir ~/.config/nvim
mkdir ~/.config/rofi
cp style.css config ~/.config/waybar/
cp config.rasi ~/.config/rofi/
cp hyprland ~/.config/hypr/
exit
echo "Do you want to use a static wallpapper deamon or do you want to use a dynamic wallpaper daemon (dynamic/static)"
read userch
while ["$(userch)" != "static" ] && ["$(userch)" != "dynamic" ]; do
	if ["$(userch)" == "static" ]; then
		pacman -S hyprpaper
		break
	fi
	if ["$(userch)" == "dynamic" ]; then
		pacman -S swww
		sed -i -e 's/exec-once = waybar & hyprpaper/exec-once = waybar & swww-daemon'
		break
	fi
	echo "please give valid response"
	read userch
done
exit
umount -R /mnt
clear
echo "installation is finished rebooting"
wait 3
exit

